apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-operator-controller
  namespace: app
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
      - deletecollection
  - apiGroups:
      - ""
    resources:
      - configmaps
      - persistentvolumeclaims
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - patch
  - apiGroups:
      - extensions
      - networking.k8s.io
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - delete
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - sparkapplications
      - scheduledsparkapplications
      - sparkconnects
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - sparkoperator.k8s.io
    resources:
      - sparkapplications/status
      - sparkapplications/finalizers
      - scheduledsparkapplications/status
      - scheduledsparkapplications/finalizers
      - sparkconnects/status
      - sparkconnects/finalizers
    verbs:
      - get
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-operator-controller
  namespace: app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-operator-controller
subjects:
  - kind: ServiceAccount
    name: spark-operator-controller
    namespace: spark-operator
