apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: app
spec:
  serviceName: "minio"
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-07-04T14-25-45Z
          args:
            - server
            - --console-address
            - ":9001"
            - /data
          envFrom:
            - configMapRef:
                name: minio-env
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-storage
              mountPath: /data
          resources:
            requests:
              cpu: 50m
              memory: 100M
            limits:
              cpu: 100m
              memory: 200M
  volumeClaimTemplates:
    - metadata:
        name: minio-storage
      spec:
        storageClassName: standard-rwo
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: app
  labels:
    app: minio
spec:
  ports:
    - port: 9000
      name: minio
    - port: 9001
      name: minio-console
  selector:
    app: minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: app
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - minio.nukenake.xyz
      secretName: minio-nukenake-xyz-tls
  rules:
    - host: minio.nukenake.xyz
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio
                port:
                  number: 9001
