apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: backend-api:local
          imagePullPolicy: IfNotPresent
          command: ["yarn", "run", "start:prod"]
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: backend-api-env
          resources:
            requests:
              cpu: 150m
              memory: 300M
          livenessProbe:
            httpGet:
              path: /api
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /api
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: app
  labels:
    app: backend-api
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: backend-api
