apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
        - name: loki
          image: grafana/loki:3.1.1
          args:
            - -config.file=/etc/loki/config.yml
          ports:
            - name: http
              containerPort: 3100
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 600Mi
          volumeMounts:
            - name: config
              mountPath: /etc/loki
            - name: data
              mountPath: /loki
      volumes:
        - name: config
          configMap:
            name: loki-config
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitor
spec:
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: http

