apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-exporter
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse-exporter
  template:
    metadata:
      labels:
        app: clickhouse-exporter
    spec:
      containers:
        - name: clickhouse-exporter
          image: f1yegor/clickhouse-exporter:latest
          args:
            - -scrape_uri=http://default:62c54f9f458d920faa0c@clickhouse.app.svc.cluster.local:8123/
          ports:
            - name: metrics
              containerPort: 9116
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 250m
              memory: 250Mi
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse-exporter
  namespace: monitor
spec:
  selector:
    app: clickhouse-exporter
  ports:
    - name: metrics
      port: 9116
      targetPort: metrics
