apiVersion: v1
kind: ConfigMap
metadata:
  name: blackbox-exporter-config
  namespace: monitor
data:
  config.yml: |
    modules:
      http_2xx:
        prober: http
        timeout: 5s
        http:
          valid_http_versions:
            - HTTP/1.1
            - HTTP/2.0
          preferred_ip_protocol: ip4
          follow_redirects: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter
  namespace: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      containers:
        - name: blackbox-exporter
          image: prom/blackbox-exporter:v0.25.0
          args:
            - --config.file=/etc/blackbox-exporter/config.yml
          ports:
            - name: metrics
              containerPort: 9115
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 150Mi
          volumeMounts:
            - name: config
              mountPath: /etc/blackbox-exporter
      volumes:
        - name: config
          configMap:
            name: blackbox-exporter-config
---
apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: monitor
spec:
  selector:
    app: blackbox-exporter
  ports:
    - name: metrics
      port: 9115
      targetPort: metrics

